### ISSUE TITLE
File won’t import into hand2note4

### ISSUE THREAD

**Issue by speedboattoyota** [charlestudor/PokerNowLogConverter#12]
Hi, I have been using your script to import logs into hand2note3 but it doesn’t seem to work for hand2note4. There don’t appear to be any error messages that I can see. Any idea why this might be the case?

**Comment by charlestudor** [comment]
Hey speedboat,

I'm afraid I'm not really sure why this might be happening, if there were
errors they would be at the point you upload the file into hand2note. If
there is any support available for that tool perhaps you can provide the
input file to them and find out what part of the log syntax their tool is
unhappy with. If the converter is not sticking to the PokerStars spec
somehow we can update it so that it does.

Thanks,
Charles

**Comment by speedboattoyota** [comment]
No worries, their support suggested I reach out to you. All good.
